repos:
  -   repo: local
      hooks:
        - id: isort
          name: isort
          entry: isort
          language: python
          args: ["--settings-path=setup.cfg"]
          types: [python]

  -   repo: local
      hooks:
      -   id: flake8
          name: flake8
          description: wemake-python-styleguide enforcement
          entry: flake8
          args: ["--config=setup.cfg"]
          language: python
          types: [python]

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.1.1
      hooks:
      -   id: mypy
          args: [--no-strict-optional, --ignore-missing-imports, --config-file=setup.cfg]
          name: mypy
          entry: mypy
          language: python
          exclude: 'tests'
          types: [python]
          additional_dependencies:
            - "types-redis==4.5.5.2"
            - "types-pytz==2023.3.1.1"


