version: '3.8'

services:

  admin_site:
    ports:
      - "8000:8000"

  frontend:
    ports:
      - "3000:3000"

  nginx:
    ports:
      - "80:80"

  postgres:
    ports:
      - "5432:5432"

  rabbitmq:
    ports:
      - "15672:15672"
