version: '3.8'

services:

  admin_site:
    build: backend/
    restart: always
    expose:
      - "8000"
    volumes:
      - static_backend:/opt/app/static/
      - media:/opt/app/media/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    command: uwsgi --strict --ini uwsgi.ini
    networks:
      - voucher_app

  api_receiver:
    build:
      context: worker_v2/api_receive
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files_data:/tmp
      - media:/opt/app/media/:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - voucher_app

  html_to_pdf:
    build:
      context: worker_v2/html_to_pdf
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files_data:/tmp
      - media:/opt/app/media/:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - voucher_app
    deploy:
      mode: replicated
      replicas: 5

  pdf_to_zip:
    build:
      context: worker_v2/pdfs_to_zip
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files_data:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - voucher_app

  send_zip:
    build:
      context: worker_v2/send_zip
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files_data:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - voucher_app

  send_zip_sharepoint:
    build:
      context: worker_v2/upload_to_sp
      dockerfile: Dockerfile
    restart: always
    volumes:
      - files_data:/tmp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /nfs/vouchers_storage:/opt/app/storage
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - voucher_app

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_backend:/var/www/backend/:ro
      - media:/var/www/media/:ro
      - frontend:/var/www/frontend/:ro
      - ./tmp/logs/nginx:/var/log/nginx/
    depends_on:
      - admin_site
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    networks:
      - voucher_app

  postgres:
    image: postgres:14.6-alpine3.17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts_postgres_only/:/docker-entrypoint-initdb.d/
    env_file:
      - .env
    networks:
      - voucher_app

  rabbitmq:
    image: rabbitmq:3.11.7-management-alpine
    restart: always
    env_file:
      - .env
    healthcheck:
        test: ["CMD", "nc", "-z", "localhost", "5672" ]
        interval: 10s
        timeout: 10s
        retries: 5
    networks:
      - voucher_app

  frontend:
    build:
      context: ./frontend
    tty: true
    restart: always
    volumes:
      - frontend:/app/build/static
    command: npm run start
    env_file:
      - .env
    networks:
      - voucher_app

  redis:
    image: redis:7.0.8-alpine
    restart: always
    networks:
      - voucher_app


volumes:
  media:
  postgres_data:
  static_frontend:
  static_backend:
  frontend:
  files_data:

networks:
  voucher_app:
    external: true

