version: '3.8'

services:

  admin_site:
    build: backend/
    expose:
      - "8000"
    volumes:
      - static:/opt/app/static/
      - media:/opt/app/media/
    env_file:
      - .env
    command: uwsgi --strict --ini uwsgi.ini
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/static/:ro
      - media:/var/www/media/:ro
    depends_on:
      - admin_site
    ports:
      - "80:80"

volumes:
  static:
  media:

networks: 
  default:
    name: voucher_app_net

