version: '3.9'
services:
  logstash:
    image: logstash:8.6.2
    ports:
      - "5044:5044/udp"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    depends_on:
      - elasticsearch
    environment:
      - XPACK_MONITORING_ENABLED=false
      - ES_HOST=elasticsearch:9200
    command: logstash -f /config/logstash.conf

  elasticsearch:
    image: elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./deploy/esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    env_file:
      - .env
  
  kibana:
    image: kibana:8.6.2
    environment:
      - SERVER_NAME=10.0.10.234
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    env_file:
      - .env

networks:
  elastic:
    name: elastic
    driver: bridge
