# Generated by Django 4.1.5 on 2023-01-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(db_column='lID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='ClientOrder_strName', max_length=100, verbose_name='Наименование заказа')),
            ],
            options={
                'db_table': 'tblClientOrder',
                'managed': False,
            },
        ),
    ]
