# Generated by Django 4.1.5 on 2023-01-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_module', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.IntegerField(db_column='lID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblClientOrderItem',
                'managed': False,
            },
        ),
    ]
