# Generated by Django 4.1.5 on 2023-01-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_module', '0003_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.IntegerField(db_column='lID', primary_key=True, serialize=False)),
                ('voucher_code', models.CharField(db_column='nVoucherCode', max_length=30)),
                ('description', models.CharField(db_column='sDescription', max_length=50)),
            ],
            options={
                'db_table': 'tblVoucherType',
                'managed': False,
            },
        ),
    ]
