# Generated by Django 4.1.5 on 2023-02-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vista_module', '0004_vouchertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'ordering': ['-order_date', 'order_id']},
        ),
    ]
