# Generated by Django 4.1.5 on 2023-02-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vista_module', '0005_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': False, 'ordering': ['customer_name']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'managed': False, 'ordering': ['order_item_id']},
        ),
        migrations.AlterModelOptions(
            name='vouchertype',
            options={'managed': False, 'ordering': ['voucher_description']},
        ),
    ]
