# Generated by Django 4.1.5 on 2023-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vista_module', '0006_alter_customer_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('voucher_number', models.IntegerField(db_column='lVoucherNumber', primary_key=True, serialize=False)),
                ('stock_strbarcode', models.CharField(db_column='Stock_strBarcode', max_length=50)),
                ('expiry_date', models.CharField(db_column='dExpiryDate', max_length=50)),
                ('issued_date', models.CharField(db_column='dIssuedDate', max_length=50)),
            ],
            options={
                'db_table': 'tblStock',
                'ordering': ['voucher_number'],
                'managed': False,
            },
        ),
    ]
