# Generated by Django 4.1.5 on 2023-10-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vista_module", "0007_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedeemedCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_type_id", models.IntegerField(db_column="lVoucherTypeID")),
                ("voucher_number", models.IntegerField(db_column="lVoucherNumber")),
                ("duplicate_no", models.IntegerField(db_column="nDuplicateNo")),
                (
                    "price",
                    models.DecimalField(
                        db_column="mAlternatePrice", decimal_places=2, max_digits=8
                    ),
                ),
            ],
            options={
                "db_table": "tblRedeemed",
                "ordering": ["voucher_type_id", "voucher_number", "duplicate_no"],
                "managed": False,
            },
        ),
    ]
