# Generated by Django 4.1.5 on 2023-06-01 07:45

import uuid
from typing import Any

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[Any] = []

    operations = [
        migrations.CreateModel(
            name="TemplatePropertyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="PropertyType"
                    ),
                ),
                (
                    "template_value",
                    models.CharField(max_length=60, verbose_name="HTML representation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TemplateProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_value", models.TextField(verbose_name="Property value")),
                (
                    "property_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voucher_app.templatepropertytype",
                    ),
                ),
            ],
            options={
                "verbose_name": "TemplateProperty",
                "verbose_name_plural": "TemplateProperties",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, unique=True, verbose_name="title"),
                ),
                (
                    "template_content",
                    models.TextField(blank=True, verbose_name="template_content"),
                ),
                (
                    "logo_image",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/", verbose_name="logo"
                    ),
                ),
                (
                    "voucher_image",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/",
                        verbose_name="voucher_image",
                    ),
                ),
                (
                    "properties",
                    models.ManyToManyField(
                        related_name="templates", to="voucher_app.templateproperty"
                    ),
                ),
            ],
            options={
                "verbose_name": "Template",
                "verbose_name_plural": "Templates",
                "db_table": 'voucher_app"."template',
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="RequestOrder",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_item", models.IntegerField()),
                (
                    "addresses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "request_id",
                    models.CharField(max_length=255, verbose_name="Request ID"),
                ),
                ("username", models.CharField(max_length=255, verbose_name="username")),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="voucher_app.template",
                    ),
                ),
            ],
            options={
                "verbose_name": "RequestOrder",
                "verbose_name_plural": "RequestOrders",
                "db_table": 'voucher_app"."request_order',
                "ordering": ["id"],
            },
        ),
    ]
