# Generated by Django 4.1.5 on 2023-06-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="properties",
            field=models.ManyToManyField(
                related_name="templates",
                to="voucher_app.templateproperty",
                verbose_name="AAAAAAAAAA",
            ),
        ),
    ]
