# Generated by Django 4.1.5 on 2023-01-22 08:31

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='RequestOrder',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Voucher_Type', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voucher_app.template')),
            ],
            options={
                'verbose_name': 'RequestOrder',
                'verbose_name_plural': 'RequestOrders',
                'db_table': 'voucher_app"."request_order',
                'ordering': ['id'],
            },
        ),
    ]
