# Generated by Django 4.1.5 on 2023-06-01 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0002_alter_template_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateproperty",
            name="property_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="voucher_app.templatepropertytype",
                verbose_name="BBBBBBBBBBBB",
            ),
        ),
    ]
