# Generated by Django 4.1.5 on 2023-01-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0003_requestorder_addresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestorder',
            name='Voucher_Type',
        ),
    ]
