# Generated by Django 4.1.5 on 2023-06-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0004_alter_template_properties_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatepropertytype",
            name="name",
            field=models.CharField(max_length=60, verbose_name="PropertyType"),
        ),
    ]
