# Generated by Django 4.1.5 on 2023-01-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0005_requestorder_voucher_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestorder',
            old_name='voucher_type',
            new_name='order_item',
        ),
    ]
