# Generated by Django 4.1.5 on 2023-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0006_rename_voucher_type_requestorder_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
