# Generated by Django 4.1.5 on 2023-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0007_template_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestorder',
            name='qr_code',
            field=models.CharField(blank=True, default=False, max_length=15, null=True, verbose_name='QRCode'),
        ),
    ]
