# Generated by Django 4.1.5 on 2023-06-01 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0007_alter_templateproperty_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="properties",
        ),
        migrations.RemoveField(
            model_name="templateproperty",
            name="property_type",
        ),
        migrations.AddField(
            model_name="templateproperty",
            name="property_name",
            field=models.CharField(
                default="", max_length=60, verbose_name="Property name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="templateproperty",
            name="template",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="voucher_app.template",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TemplatePropertyType",
        ),
    ]
