# Generated by Django 4.1.5 on 2023-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0008_requestorder_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestorder',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='requestorder',
            name='code_type',
            field=models.CharField(blank=True, default=False, max_length=15, null=True, verbose_name='CodeType'),
        ),
    ]
