# Generated by Django 4.1.5 on 2023-01-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0009_remove_requestorder_qr_code_requestorder_code_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestorder',
            name='code_type',
        ),
    ]
