# Generated by Django 4.1.5 on 2023-06-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0009_templateproperty_property_locale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateproperty",
            name="property_value",
            field=models.TextField(
                blank=True, null=True, verbose_name="Property value"
            ),
        ),
    ]
