# Generated by Django 4.1.5 on 2023-06-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0010_alter_templateproperty_property_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateproperty",
            name="property_value",
            field=models.TextField(default="", verbose_name="Property value"),
            preserve_default=False,
        ),
    ]
