# Generated by Django 4.1.5 on 2023-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0011_alter_template_template_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='template_content',
            field=models.TextField(blank=True, verbose_name='template_content'),
        ),
    ]
