# Generated by Django 4.1.5 on 2023-10-11 13:38

from django.db import migrations

import voucher_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher_app", "0011_alter_templateproperty_property_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templateproperty",
            name="property_name",
            field=voucher_app.models.NameFieldRO(
                max_length=60, verbose_name="Property name"
            ),
        ),
    ]
