# Generated by Django 4.1.5 on 2023-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0012_alter_template_template_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='logo',
            new_name='logo_image',
        ),
        migrations.AddField(
            model_name='template',
            name='voucher_image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
