# Generated by Django 4.1.5 on 2023-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0013_rename_logo_template_logo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='logo_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='voucher_b64',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
