# Generated by Django 4.1.5 on 2023-02-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_app', '0014_template_logo_b64_template_voucher_b64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='logo_b64',
        ),
        migrations.RemoveField(
            model_name='template',
            name='voucher_b64',
        ),
    ]
